//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proba22
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Вакант должн.
    /// </summary>
    // *** Start programmer edit section *** (ВакантДолжн CustomAttributes)

    // *** End programmer edit section *** (ВакантДолжн CustomAttributes)
    [AutoAltered()]
    [Caption("Вакант должн")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ВакантДолжнE", new string[] {
            "Должности as \'Должности\'",
            "IDДолжности as \'I d должности\'"})]
    [View("ВакантДолжнL", new string[] {
            "Должности as \'Должности\'",
            "IDДолжности as \'I d должности\'"})]
    public class ВакантДолжн : ICSSoft.STORMNET.DataObject
    {
        
        private string fДолжности;
        
        private int fIDДолжности;
        
        // *** Start programmer edit section *** (ВакантДолжн CustomMembers)

        // *** End programmer edit section *** (ВакантДолжн CustomMembers)

        
        /// <summary>
        /// IDДолжности.
        /// </summary>
        // *** Start programmer edit section *** (ВакантДолжн.IDДолжности CustomAttributes)

        // *** End programmer edit section *** (ВакантДолжн.IDДолжности CustomAttributes)
        public virtual int IDДолжности
        {
            get
            {
                // *** Start programmer edit section *** (ВакантДолжн.IDДолжности Get start)

                // *** End programmer edit section *** (ВакантДолжн.IDДолжности Get start)
                int result = this.fIDДолжности;
                // *** Start programmer edit section *** (ВакантДолжн.IDДолжности Get end)

                // *** End programmer edit section *** (ВакантДолжн.IDДолжности Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВакантДолжн.IDДолжности Set start)

                // *** End programmer edit section *** (ВакантДолжн.IDДолжности Set start)
                this.fIDДолжности = value;
                // *** Start programmer edit section *** (ВакантДолжн.IDДолжности Set end)

                // *** End programmer edit section *** (ВакантДолжн.IDДолжности Set end)
            }
        }
        
        /// <summary>
        /// Должности.
        /// </summary>
        // *** Start programmer edit section *** (ВакантДолжн.Должности CustomAttributes)

        // *** End programmer edit section *** (ВакантДолжн.Должности CustomAttributes)
        [StrLen(255)]
        public virtual string Должности
        {
            get
            {
                // *** Start programmer edit section *** (ВакантДолжн.Должности Get start)

                // *** End programmer edit section *** (ВакантДолжн.Должности Get start)
                string result = this.fДолжности;
                // *** Start programmer edit section *** (ВакантДолжн.Должности Get end)

                // *** End programmer edit section *** (ВакантДолжн.Должности Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВакантДолжн.Должности Set start)

                // *** End programmer edit section *** (ВакантДолжн.Должности Set start)
                this.fДолжности = value;
                // *** Start programmer edit section *** (ВакантДолжн.Должности Set end)

                // *** End programmer edit section *** (ВакантДолжн.Должности Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ВакантДолжнE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВакантДолжнE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВакантДолжнE", typeof(IIS.Proba22.ВакантДолжн));
                }
            }
            
            /// <summary>
            /// "ВакантДолжнL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВакантДолжнL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВакантДолжнL", typeof(IIS.Proba22.ВакантДолжн));
                }
            }
        }
    }
}
