//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proba22
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Граф собес.
    /// </summary>
    // *** Start programmer edit section *** (ГрафСобес CustomAttributes)

    // *** End programmer edit section *** (ГрафСобес CustomAttributes)
    [AutoAltered()]
    [Caption("Граф собес")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ГрафСобесE", new string[0])]
    [View("ГрафСобесL", new string[0])]
    public class ГрафСобес : ICSSoft.STORMNET.DataObject
    {
        
        // *** Start programmer edit section *** (ГрафСобес CustomMembers)

        // *** End programmer edit section *** (ГрафСобес CustomMembers)

        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ГрафСобесE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГрафСобесE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГрафСобесE", typeof(IIS.Proba22.ГрафСобес));
                }
            }
            
            /// <summary>
            /// "ГрафСобесL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГрафСобесL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГрафСобесL", typeof(IIS.Proba22.ГрафСобес));
                }
            }
        }
    }
}
