//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proba22
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ДолжнСотр.
    /// </summary>
    // *** Start programmer edit section *** (ДолжнСотр CustomAttributes)

    // *** End programmer edit section *** (ДолжнСотр CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДолжнСотрE", new string[] {
            "Должность as \'Должность\'",
            "ФИОСотр as \'Ф и о сотр\'"})]
    [View("ДолжнСотрL", new string[] {
            "Должность as \'Должность\'",
            "ФИОСотр as \'Ф и о сотр\'"})]
    public class ДолжнСотр : ICSSoft.STORMNET.DataObject
    {
        
        private string fДолжность;
        
        private string fФИОСотр;
        
        // *** Start programmer edit section *** (ДолжнСотр CustomMembers)

        // *** End programmer edit section *** (ДолжнСотр CustomMembers)

        
        /// <summary>
        /// Должность.
        /// </summary>
        // *** Start programmer edit section *** (ДолжнСотр.Должность CustomAttributes)

        // *** End programmer edit section *** (ДолжнСотр.Должность CustomAttributes)
        [StrLen(255)]
        public virtual string Должность
        {
            get
            {
                // *** Start programmer edit section *** (ДолжнСотр.Должность Get start)

                // *** End programmer edit section *** (ДолжнСотр.Должность Get start)
                string result = this.fДолжность;
                // *** Start programmer edit section *** (ДолжнСотр.Должность Get end)

                // *** End programmer edit section *** (ДолжнСотр.Должность Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДолжнСотр.Должность Set start)

                // *** End programmer edit section *** (ДолжнСотр.Должность Set start)
                this.fДолжность = value;
                // *** Start programmer edit section *** (ДолжнСотр.Должность Set end)

                // *** End programmer edit section *** (ДолжнСотр.Должность Set end)
            }
        }
        
        /// <summary>
        /// ФИОСотр.
        /// </summary>
        // *** Start programmer edit section *** (ДолжнСотр.ФИОСотр CustomAttributes)

        // *** End programmer edit section *** (ДолжнСотр.ФИОСотр CustomAttributes)
        [StrLen(255)]
        public virtual string ФИОСотр
        {
            get
            {
                // *** Start programmer edit section *** (ДолжнСотр.ФИОСотр Get start)

                // *** End programmer edit section *** (ДолжнСотр.ФИОСотр Get start)
                string result = this.fФИОСотр;
                // *** Start programmer edit section *** (ДолжнСотр.ФИОСотр Get end)

                // *** End programmer edit section *** (ДолжнСотр.ФИОСотр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДолжнСотр.ФИОСотр Set start)

                // *** End programmer edit section *** (ДолжнСотр.ФИОСотр Set start)
                this.fФИОСотр = value;
                // *** Start programmer edit section *** (ДолжнСотр.ФИОСотр Set end)

                // *** End programmer edit section *** (ДолжнСотр.ФИОСотр Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДолжнСотрE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДолжнСотрE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДолжнСотрE", typeof(IIS.Proba22.ДолжнСотр));
                }
            }
            
            /// <summary>
            /// "ДолжнСотрL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДолжнСотрL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДолжнСотрL", typeof(IIS.Proba22.ДолжнСотр));
                }
            }
        }
    }
}
